### ISSUE TITLE
All playback fails

### ISSUE THREAD

**Issue by felixyz** [asciidisco/plugin.video.netflix#206]
*I'm submitting a ...*
  - [ x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

Browsing works, video playback fails. ("License update not successful".)

### Prerequisites

* [x] Are you running the latest version?
0.14.2

### Steps to Reproduce

Select a show and try to watch it.

## Context (Environment)

Brand new Vero 4k running OSMC 2017.09-2, kernel 14.29-37, Kodi 18.0-ALPHA1

Running `dpkg -l | grep mediacenter-osmc` prints

`ii  vero3-mediacenter-osmc               17.8-118                           armhf        Media Center package for OSMC`

But I am running Kodi 18-
### Installation

* [x] I installed the plugin via zip from the Releases page

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://gist.github.com/felixyz/9bfdf0e50b85a681cf1359a63f659c65

**Comment by asciidisco** [comment]
Currently a bug setting the correct ESN for Android. Fix will be pushed this evening.

**Comment by asciidisco** [comment]
Fixed in 0.12.5, you might need to clear (empty & save) the ESN field in your settings

**Comment by felixyz** [comment]
Sorry, still not working for me:

```
21:52:55.783 T:4113760816 WARNING: Previous line repeats 36 times.
21:52:55.783 T:4113760816  NOTICE: VideoPlayer::OpenFile: http://localhost:57149/manifest?id=80087549
21:52:55.784 T:3697239024  NOTICE: Creating InputStream
21:53:00.622 T:3746427888   ERROR: Traceback (most recent call last):
21:53:00.623 T:3746427888   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
21:53:00.624 T:3746427888   ERROR:     self.process_request(request, client_address)
21:53:00.624 T:3746427888   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
21:53:00.624 T:3746427888   ERROR:     self.finish_request(request, client_address)
21:53:00.624 T:3746427888   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
21:53:00.625 T:3746427888   ERROR:     self.RequestHandlerClass(request, client_address, self)
21:53:00.625 T:3746427888   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
21:53:00.625 T:3746427888   ERROR:     self.handle()
21:53:00.625 T:3746427888   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
21:53:00.626 T:3746427888   ERROR:     self.handle_one_request()
21:53:00.627 T:3746427888   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
21:53:00.627 T:3746427888   ERROR:     method()
21:53:00.628 T:3746427888   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 41, in do_POST
21:53:00.629 T:3746427888   ERROR:     self.wfile.write(base64.standard_b64decode(b64license))
21:53:00.629 T:3746427888   ERROR:   File "/usr/lib/python2.7/base64.py", line 93, in standard_b64decode
21:53:00.630 T:3746427888   ERROR:     return b64decode(s)
21:53:00.630 T:3746427888   ERROR:   File "/usr/lib/python2.7/base64.py", line 73, in b64decode
21:53:00.630 T:3746427888   ERROR:     return binascii.a2b_base64(s)
21:53:00.630 T:3746427888   ERROR: TypeError: must be string or buffer, not bool
21:53:00.634 T:3697239024   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
21:53:00.634 T:3697239024   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
21:53:00.636 T:3697239024   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:57149/manifest?id=80087549]
21:53:00.637 T:3697239024  NOTICE: CVideoPlayer::OnExit()
```

With 0.12.6.

Again, I'm running on a Vero 4K (osmc).

I must admit I don't know how to **clear (empty & save) the ESN field**. In which settings? Or from CLI?

**Comment by asciidisco** [comment]
Navigate to the addons settings & there to the "Expert" session.
Just click on that ESN field & remove all chars. Then reboot Kodi or your device (just for the sake of safety) & it *should* work again. 
![screen shot 2017-10-26 at 20 30 26](https://user-images.githubusercontent.com/805339/32070475-c2b06b5a-ba8c-11e7-9f1d-6c2e2b1bfa46.png)

**Comment by martinpfannemueller** [comment]
I get exactly the same error using 0.12.7. I am also using a Vero 4k. Complete stacktrace:

`19:18:44.505 T:3696784368   ERROR: Traceback (most recent call last):
19:18:44.505 T:3696784368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
19:18:44.505 T:3696784368   ERROR:     self.process_request(request, client_address)
19:18:44.505 T:3696784368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
19:18:44.506 T:3696784368   ERROR:     self.finish_request(request, client_address)
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
19:18:44.506 T:3696784368   ERROR:     self.RequestHandlerClass(request, client_address, self)
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
19:18:44.506 T:3696784368   ERROR:     self.handle()
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
19:18:44.506 T:3696784368   ERROR:     self.handle_one_request()
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
19:18:44.506 T:3696784368   ERROR:     method()
19:18:44.506 T:3696784368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 41, in do_POST
19:18:44.506 T:3696784368   ERROR:     self.wfile.write(base64.standard_b64decode(b64license))
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/base64.py", line 93, in standard_b64decode
19:18:44.506 T:3696784368   ERROR:     return b64decode(s)
19:18:44.506 T:3696784368   ERROR:   File "/usr/lib/python2.7/base64.py", line 73, in b64decode
19:18:44.506 T:3696784368   ERROR:     return binascii.a2b_base64(s)
19:18:44.506 T:3696784368   ERROR: TypeError: must be string or buffer, not bool
19:18:44.547 T:4016042992   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
19:18:44.547 T:4016042992   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)`

Clearing the ESN field and rebooting did not help for me. Any other idea how to fix this? Thanks a lot!
