### ISSUE TITLE
Subtitles disabled when video is rewinded

### ISSUE THREAD

**Issue by raven6679** [asciidisco/plugin.video.netflix#234]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Kodi 18 + Netflix plugin (latest). When video is rewinded or step back, subtitles dissappears and it's necessary to toggle subtitles in order to get them back. 

### Prerequisites

* [X] Are you running the latest version?

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by asciidisco** [comment]
Sounds like an inputstream or Kodi issue to me. @peak3d may I ask you to have a look?

**Comment by raven6679** [comment]
It isn't Kodi issue itself. This won't happen if you watch local movie from disk. Only in Netflix plugin.

**Comment by peak3d** [comment]
should be fixed with the latest inputstream.adaptive version (for kodi 18), it was not yet backported to the Krypton branch.

**Comment by raven6679** [comment]
Soooo, should I do sth? I've updated all the libraries and plugins and problem still persists. Sorry for stupid question, but I'm rather lame in terms of video playback and dependencies.

**Comment by peak3d** [comment]
A log file helps in most cases

**Comment by HiassofT** [comment]
@peak3d here's a debug log of current (1218) milhouse build: http://sprunge.us/ZALj

played S01E01 of marvel's defenders, seek to 11:00, enable subtitles, seek back - subtitles gone, try to disable and enable subtitles without effect

**Comment by HiassofT** [comment]
inputstream.adaptive version 2.1.10 fixed the issue here
