### ISSUE TITLE
Login not successful - Request error

### ISSUE THREAD

**Issue by fofinho11** [asciidisco/plugin.video.netflix#344]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

Error message on login. Checked the credentials few times, they are correct. Says login is not successful and gives a request error.

### Steps to Reproduce

1. [Install LE 9]
2. [Install Netflix add-on]
3. [Login]

**Expected behavior:** [What you expected to happen]
It should log me in :)

**Actual behavior:** [What actually happened]
Error message described above

### Installation

* [] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.com/SacybRQw

**Comment by fofinho11** [comment]
New log with 0.13.2

https://pastebin.com/92Sr72Lh

**Comment by liberty-developer** [comment]
@fofinho11 your issues should be fixed with 0.13.3

**Comment by fofinho11** [comment]
Hey, thanks for your reply. I downloaded 0.13.3 but it still doesn't work. Gives same error message but when I press backspace on my keyboard Kodi freezes and I have to reboot. Here's a new log:

https://pastebin.com/6LMZwYiz

Appreciate your help

**Comment by liberty-developer** [comment]
This is a kodi bug, pls. use latest milhouse + latest addon (0.13.4)

**Comment by fofinho11** [comment]
Didn't work after the update.
Created new Netflix account for testing purposes.
Works with that account...

Might special characters in the Netflix profile name be the problem? There's an emoji in it... 🤔

**Comment by liberty-developer** [comment]
can you confirm, that 0.13.8 is working?

**Comment by caphm** [comment]
Sorry for commenting on this closed issue, but:

@fofinho11 yes that is an issue. See my first comment on #315. You'll have to rename your profile.
